{% set name = "tangram_cauchian" %}


package:
  name: {{ name|lower }}
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'v')[1:] }}

source:
  url: ../

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
  run:
    - python
    - pychimera     >=0.2.6
    - libtangram
    - sqlite

about:
  home: http://github.com/insilichem/tangram_cauchian
  license: MIT
  license_family: MIT

  summary: 'QM and QM/MM calculations setup for UCSF Chimera'

  description: |
    QM and QM/MM calculations setup for UCSF Chimera
  doc_url: http://tangram-suite.readthedocs.io/en/latest/tangram_cauchian.html
  dev_url: https://github.com/insilichem/tangram_cauchian


